GET http://localhost:8080/symbols/name/pk007
Accept: application/json

###
GET http://localhost:8080/symbols/name/lt007
Accept: application/json

###
GET http://localhost:8080/symbols/name/vag502
Accept: application/json

###
GET http://localhost:8080/symbols/1
Accept: application/json

###
GET http://localhost:8080/symbols/15
Accept: application/json

###
GET http://localhost:8080/symbols/186
Accept: application/json

###
GET http://localhost:8080/symbols/lookup/vag
Accept: application/json

###

GET http://localhost:8080/symbols/lookup/lt
Accept: application/json

###

GET http://localhost:8080/symbols/lookup/lm
Accept: application/json

###
GET http://localhost:8080/symbols/lookup/ls
Accept: application/json

###
GET http://localhost:8080/symbols/lookup/%5Cnlt
Accept: application/json