info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'

management:
  endpoint:
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      path-mapping:
        info: app-info
        health: app-health
      exposure:
        include: '*'
        exclude:
    enabled-by-default: true
  info:
    env:
      enabled: true
    git:
      mode: full
      enabled: true
  server:
    port: 8081
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: @project.name@
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/symbol
    username: testuser
    password: 12345
  jpa:
    database: postgresql
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        format_sql: true
        jdbc:
          batch_size: 100
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false