import { Symbol } from "./symbol";

export const SYMBOLS: Symbol [] = [
  {
    "id": 2409,
    "type": "Lijn",
    "size": 0,
    "rotation": 0,
    "fill": null,
    "fillopacity": 0,
    "stroke": "#000000",
    "strokeopacity": 1,
    "strokewidth": 8,
    "stokelinecap": "butt",
    "strokedasharray": null,
    "strokelinejoinfill": null,
    "strokelinejoinstroke": null,
    "symbol": null,
    "name": "lt000"
  },
  {
    "id": 2410,
    "type": "Lijn",
    "size": 0,
    "rotation": 0,
    "fill": null,
    "fillopacity": 0,
    "stroke": "#ebf0d2",
    "strokeopacity": 1,
    "strokewidth": 8,
    "stokelinecap": "butt",
    "strokedasharray": null,
    "strokelinejoinfill": null,
    "strokelinejoinstroke": null,
    "symbol": null,
    "name": "lt001"
  },
  {
    "id": 5459,
    "type": "Punt",
    "size": 0,
    "rotation": 0,
    "fill": "#ebf0d2",
    "fillopacity": 1,
    "stroke": "#999999",
    "strokeopacity": 0,
    "strokewidth": 1,
    "stokelinecap": null,
    "strokedasharray": null,
    "strokelinejoinfill": null,
    "strokelinejoinstroke": null,
    "symbol": null,
    "name": "pc001",
    "welknownname": "circle"
  },
  {
    "id": 5460,
    "type": "Punt",
    "size": 0,
    "rotation": 0,
    "fill": "#d2ffa5",
    "fillopacity": 1,
    "stroke": "#999999",
    "strokeopacity": 0,
    "strokewidth": 1,
    "stokelinecap": null,
    "strokedasharray": null,
    "strokelinejoinfill": null,
    "strokelinejoinstroke": null,
    "symbol": null,
    "name": "pc002",
    "welknownname": "circle"
  },
  {
    "id": 2897,
    "type": "Vlak",
    "size": 0,
    "rotation": 0,
    "fill": null,
    "fillopacity": 0,
    "stroke": "#d2ffa5",
    "strokeopacity": 1,
    "strokewidth": 2,
    "stokelinecap": null,
    "strokedasharray": null,
    "strokelinejoinfill": null,
    "strokelinejoinstroke": "round",
    "symbol": "va002.png",
    "name": "vag002"
  },
  {
    "id": 2898,
    "type": "Vlak",
    "size": 0,
    "rotation": 0,
    "fill": null,
    "fillopacity": 0,
    "stroke": "#b45fd2",
    "strokeopacity": 1,
    "strokewidth": 2,
    "stokelinecap": null,
    "strokedasharray": null,
    "strokelinejoinfill": null,
    "strokelinejoinstroke": "round",
    "symbol": "va003.png",
    "name": "vag003"
  },
];
