-- create table area

create table area
(
    id                   bigint not null primary key,

    type                 text,
    name                 text,
    fill                 text,
    fillopacity          float,
    stroke               text,
    strokeopacity        int,
    strokewidth          float,
    strokelinejoinfill   text,
    strokelinejoinstroke text,
    strokedasharray      text,
    symbol               text
);

create unique index area_name_ix on area (name);

ALTER TABLE area
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME area_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );
