-- create table symbol

create table symbol
(
    id        bigint not null primary key,
    name      text,
    stroke    text,
    opacity   int,
    width     int,
    linecap   text,
    dasharray text
);

create unique index symbol_name_ix on symbol (name);

ALTER TABLE symbol
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME symbol_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );