-- create table symbol

create table symbol
(
    id                   bigint not null primary key,

    type                 text,
    size                 int,
    rotation             int,
    fill                 text,
    fillopacity          float,
    stroke               text,
    strokeopacity        int,
    strokewidth          int,
    stokelinecap         text,
    strokedasharray      text,
    strokelinejoinfill   text,
    strokelinejoinstroke text,
    symbol               text,
    name                 text
);

create unique index symbol_name_ix on symbol (name);

ALTER TABLE symbol
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME symbol_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );
