-- create table line

create table line
(
    id        bigint not null primary key,
    type      text,
    name      text,
    stroke    text,
    opacity   int,
    width     int,
    linecap   text,
    dasharray text
);

create unique index line_name_ix on line (name);

ALTER TABLE line
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME line_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );
